import { randomInt } from "node:crypto";
import { WORDLIST } from "./wordlist.js";

export const ROOM_CODE_DEFAULT_LENGTH = 4;
export const ROOM_CODE_MIN_LENGTH = 2;
export const ROOM_CODE_MAX_LENGTH = 6;

// Matches 2..6 segments of 3-6 lowercase ASCII chars joined by hyphens.
// EFF Short Wordlist entries are 3-5 chars; we accept up to 6 here so codes
// generated by previous wordlist versions (which included some 6-char words)
// still parse during upgrades.
const ROOM_CODE_RE = /^([a-z]{3,6}-){1,5}[a-z]{3,6}$/;

/** Resolve the configured code length from the user's plugin config.
 *  Falls back to ROOM_CODE_DEFAULT_LENGTH when unset, NaN, or out of range. */
export function resolveRoomCodeLength(): number {
  const raw = process.env.CLAUDE_PLUGIN_OPTION_ROOM_CODE_LENGTH;
  if (raw == null || raw === "") return ROOM_CODE_DEFAULT_LENGTH;
  const n = Number(raw);
  if (!Number.isInteger(n)) return ROOM_CODE_DEFAULT_LENGTH;
  if (n < ROOM_CODE_MIN_LENGTH || n > ROOM_CODE_MAX_LENGTH) return ROOM_CODE_DEFAULT_LENGTH;
  return n;
}

export function generateRoomCode(length: number = resolveRoomCodeLength()): string {
  const n = Math.max(ROOM_CODE_MIN_LENGTH, Math.min(ROOM_CODE_MAX_LENGTH, length | 0));
  const parts: string[] = [];
  for (let i = 0; i < n; i++) {
    parts.push(WORDLIST[randomInt(0, WORDLIST.length)]);
  }
  return parts.join("-");
}

export function isValidRoomCode(code: string): boolean {
  return ROOM_CODE_RE.test(code);
}

export function normalizeRoomCode(input: string): string | null {
  const trimmed = input.trim().toLowerCase();
  return isValidRoomCode(trimmed) ? trimmed : null;
}
